### ISSUE TITLE
Mesh Documentation example shows "subdivisions" instead of "subdivision"

### ISSUE THREAD

**Issue by dav-s** [gportelli/pocket.gl#3]
Hi! Love the project!

Here is the part I am talking about: http://pocket.gl/documentation/#Meshes

In the code example it says `subdivisions: numberOfSubdvisions`. However, in the description of the attribute below it spells it `subdvision`.

This was confusing to me as if you incorrectly use `subdivisions`, `mesh.subdivision` is undefined and then set to a default value, so it is hard to debug.

(I would've made a PR for this, but I couldn't find if you had a repo for the site)

**Comment by gportelli** [comment]
Thanks, I've just updated the documentation.
There is no repo for the site, just a wordpress installation.
